spring:
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:h2:mem:testdb
  sql:
    init:
      mode: always

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

    show-sql: false
    properties:
      hibernate:
        format_sql: true
